server:
  port: 8084


# Swagger界面内容配置
swagger:
  title: 班级小助理API接口文档
  description: 班级小助理API接口文档
  version: 0.0.1
  termsOfServiceUrl:
  contact:
    name: Edwin
    url: http://wiki.qtonecloud.cn/pages/viewpage.action?pageId=51875966
    email: edwin13@qq.com

spring:
  thymeleaf:
    cache: false
  # 数据源
  datasource:
#    url: ENC(jdbc_url)
#    username: ENC(jdbc_user)
#    password: ENC(jdbc_password)
    url: jdbc:mysql://127.0.0.1:3306/ripple?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
  jpa:
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      naming:
        # 驼峰命名
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 3000
  # ES
  elasticsearch:
    nodeClient: 127.0.0.1:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
  flyway:
    baseline-on-migrate: true
weixin:
  appid: wxc151da26a58d32ce
  secret: 0c4b859d84bfe08c722678236d982937
  apiUrl: https://api.weixin.qq.com

qky:
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7

# 忽略鉴权url
ignored:
  urls:
    - /v2/swagger.json
    - /system/ssoLogin
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.ripple.entity
  typeEnumsPackage: cn.ripple.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
